version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "5000"
  
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

